<?php
/**
 * @file Contains PDF creation functions based on TCPDF.
 * Also contatins Schema validation funcitons
 */

/**
 * Makes a PDF based on 2 XSL Template files (located in resources/cfd_*.xsl)
 * one for header, one for content and also uses SAT provided file: cadenaoriginal_2_0.xslt
 * Uses FEpdf class to define the header and footer (located in reources/FEpdf.php)
 * Custom code to word-wrap the 'cadena original' using | instead of spaces.
 * @param mixed $xml The xml string or .xml file of the CFD to convert to PDF
 * @return a TCPDF object of the converted CFD
 **/
function cfd_make_pdf($xml) {
  require_once libraries_get_path('tcpdf') . '/tcpdf.php';
  require_once drupal_get_path('module', 'cfd') . '/resources/FEpdf.php';
  //Apply XSLT
  $doc = new DOMDocument();
  //load xml data string or filename
  if (is_file($xml))
    $doc->load($xml, LIBXML_NOWARNING);
  else
    $doc->loadXML($xml);

  //Content
  $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/cfd_content.xsl';
  $xsl_content = new DOMDocument(); $xsl_content->load($xsl_content_file);
  $xsl = new XSLTProcessor(); $xsl->importStylesheet($xsl_content);
  $xsl->registerPHPFunctions('number_format');
  $html_content = $xsl->transformToXml($doc);
  //"cadena original" or cado
  $xsl_cado_file = drupal_get_path('module', 'cfd') . '/resources/sat/cadenaoriginal_2_0.xslt';
  $xsl_cado = new DOMDocument(); $xsl_cado->load($xsl_cado_file);
  // hide warnings in @...importStylesheet because it complains about xslt version 2.0
  $xsl = new XSLTProcessor(); @$xsl->importStylesheet($xsl_cado);
  $cadena_original = $xsl->transformToXml($doc);

  //generate PDF
  $pdf = new FEpdf();
  $pdf->SetMargins(10, 10, 10, TRUE);
  //Header (in FEpdf.php)
  $pdf->registerHeader($doc);
  $pdf->AddPage();

  $pdf->writeHTML($html_content.'<br />');

  //Cadena Original with word wrapping in |
  $pdf->SetY($pdf->getY() - 7);
  $pdf->SetFontSize(10);
  $pdf->writeHTML('<strong>Cadena Original</strong>');
  $pdf->SetFontSize(8);
  //word wrapping
  $cado = explode('|', substr($cadena_original, 2, -2));
  $pdf->SetCellPadding(0);
  $pdf->Write(0, '||');
  $margins = $pdf->getMargins();
  $line_width = $pdf->getPageWidth() - $margins['left'] - $margins['right'];
  $space_left = $line_width -  $pdf->GetStringWidth('||');
  $totalwords = count($cado);
  $i = 0;
  foreach ($cado as $word) {
    //if we are on the last word
    if ($i < $totalwords - 1) {
      $word_width = $pdf->GetStringWidth($word . '|');
    }
    else {
      $word_width = $pdf->GetStringWidth($word . '||');
    }

    if ($word_width > $space_left) {
      $space_left = $line_width - $word_width;
      $pdf->Ln();
    }
    else {
      $space_left -= $word_width;
    }
    $pdf->Write(0, $word . '|');
    $i++;
  }
  $pdf->Write(0, '|');
  //serve file
  $pdf->SetCreator("Drupal-CFD module with " . PDF_CREATOR);
  $pdf->SetAuthor(variable_get('site_name', 'the website'));
  return $pdf;
}

/**
 * Validates a CFD against cfdv2.xsd (XML Schema provided by SAT)
 * removes Addenda and Complemento nodes to avoid issues
 * @param mixed $xml filename or xml data to validate
 * @return bool true if it is a valid xml
 */
function cfd_validate_schema($xml) {
  $doc = new DOMDocument();
  //load xml data string or filename
  if (is_file($xml))
    $doc->load($xml, LIBXML_NOWARNING);
  else
    $doc->loadXML($xml);

  // gather problem nodes: Addenda, Complemento
  $doc_el = $doc->documentElement;
  $addenda_list     = $doc_el->getElementsByTagName('Addenda');
  $complemento_list = $doc_el->getElementsByTagName('Complemento');
  //remove these gathered nodes
  foreach($addenda_list as $addenda) {
    $doc_el->removeChild($addenda);
  }
  foreach($complemento_list as $complemento) {
    $doc_el->removeChild($complemento);
  }

  if ($doc->isDefaultNamespace('http://www.sat.gob.mx/cfd/2'))
    $schemaFileName = drupal_get_path('module', 'cfd') . '/resources/sat/cfdv2.xsd';
  else if ($doc->lookupPrefix('http://www.sat.gob.mx/cfd/3') == 'cfdi')
    $schemaFileName = drupal_get_path('module', 'cfd') . '/resources/sat/cfdv3.xsd';

  $validcfd = @$doc->schemaValidate($schemaFileName);
  return $validcfd;
}

/**
 * Validates the CFD's 'sello'
 * @param mixed $xml The xml string or .xml file of the CFD to convert to PDF
 * @return string valido, invalido or intdeterminado
 **/
function cfd_validate_sello($xml) {
  // get cadena original using SAT provided XSLT file.
  $doc = new DOMDocument();
  if (is_file($xml))
    $doc->load($xml, LIBXML_NOWARNING);
  else
    $doc->loadXML($xml);

  $xsl_content = new DOMDocument();
  $xpath = new DOMXPath($doc);
  if ($doc->isDefaultNamespace('http://www.sat.gob.mx/cfd/2')) {
    // for CFD
    $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/sat/cadenaoriginal_2_0.xslt';
    $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/2');
  }
  else if ($doc->lookupPrefix('http://www.sat.gob.mx/cfd/3') == 'cfdi') {
    // for CFDI
    $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/sat/cadenaoriginal_3_0.xslt';
    $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/3');
  }

  $year = substr($xpath->query('/cfd:Comprobante/@fecha')->item(0)->value, 0, 4);
  $certificado = $xpath->query('/cfd:Comprobante/@certificado');
  $sello = $xpath->query('/cfd:Comprobante/@sello')->item(0)->value;
  $xsl_content->load($xsl_content_file, LIBXML_NOWARNING);
  $xsl = new XSLTProcessor(); @$xsl->importStylesheet($xsl_content);
  $cadena_original = $xsl->transformToXml($doc);


  // Since @certificado is optional in a CFD
  if($certificado->length) {
    // convert $certificado into something openssl can parse
    // but first decode entities and remove whitespaces (and newlines, etc...)
    $cert = preg_replace('/\s+/', '', html_entity_decode($certificado->item(0)->value, ENT_QUOTES, 'UTF-8'));
    $pub_cer = "-----BEGIN CERTIFICATE-----\r\n";
    $pub_cer .= wordwrap($cert, 64, "\r\n", true);
    $pub_cer .= "\r\n-----END CERTIFICATE-----";
    $pub_key = openssl_pkey_get_public($pub_cer);

    if ($year <= 2010)
      $v = openssl_verify($cadena_original, base64_decode($sello), $pub_key, OPENSSL_ALGO_MD5);
    else
      $v = openssl_verify($cadena_original, base64_decode($sello), $pub_key, OPENSSL_ALGO_SHA1);

    if ($v == 1) {
      return 'valido';
    }
    else if ($v == 0) {
      return 'invalido';
    }
  } else
    return 'indeterminado';
}

/**
 * Valida el folio localmente
 */
function cfd_validate_folio($serie, $folio, $noAprobacion, $anoAprobacion, $RFC) {
  $query_string = <<<SQL
SELECT count(*) as validstatus
FROM {cfd_folios}
WHERE RFC = :RFC
AND Serie = :serie
AND noAprobacion = :noAprobacion
AND anoAprobacion = :anoAprobacion
AND :folio BETWEEN FolioInicial AND FolioFinal;
SQL;
  $result = db_query($query_string, array(
    ':serie' => $serie,
    ':folio' => $folio,
    ':noAprobacion' => $noAprobacion,
    ':anoAprobacion' => $anoAprobacion,
    ':RFC' => $RFC,
  ))->fetchAssoc();
  return $result['validstatus'];
}

/**
 * Valida el certificado localmente
 */
function cfd_validate_cert($noCertificado, $RFC, $fecha) {
  $query_string = <<<SQL
SELECT count(*) as validstatus
FROM {cfd_certs}
WHERE no_serie = :noCertificado
AND RFC = :RFC
AND :fecha BETWEEN fecha_inicial_cert AND fecha_final_cert;
SQL;
  $result = db_query($query_string, array(
    ':noCertificado' => $noCertificado,
    ':RFC' => $RFC,
    ':fecha' => $fecha,
  ))->fetchAssoc();
  return $result['validstatus'];
}


/**
 * Recive un array y regresa una cadena XML de acuerdo a la especificacion
 * @param $cfd_array estructura del array (debe usar estos nombres de 'key'):
 * array(
 *   array(
 *     'RFC'            => '...',
 *     'serie'          => '...',
 *     'folio'          => '...',
 *     'no_aprobacion'  => '...',
 *     'ano_aprobacion' => '...',
 *     'no_certificado' => '...',
 *     'fecha'          => '...',
 *   ),
 *   array(...),
 * )
 * @return string XML
 */
function _cfd_generate_multi_request_xml($cfds) {
  $ns = 'http://www.sat.gob.mx/Asf/Sicofi/ValidacionFoliosCFD/1.0.0';
  $doc = new DOMDocument('1.0', 'UTF-8');
  $root = $doc->createElementNS($ns, 'ColleccionFoliosCfd');

  $count = 1;
  foreach ($cfds as $cfd) {
    //create elements
    $folioC         = $doc->createElementNS($ns, 'Folio');
    $id             = $doc->createElementNS($ns, 'Id'                      , $count++);
    $rfc            = $doc->createElementNS($ns, 'Rfc'                     , $cfd['RFC']);
    $serie          = $doc->createElementNS($ns, 'Serie'                   , $cfd['serie']);
    $folio          = $doc->createElementNS($ns, 'NumeroFolio'             , $cfd['folio']);
    $no_aprobacion  = $doc->createElementNS($ns, 'NumeroAprobacion'        , $cfd['no_aprobacion']);
    $ano_aprobacion = $doc->createElementNS($ns, 'AnioAprobacion'          , $cfd['ano_aprobacion']);
    $no_certificado = $doc->createElementNS($ns, 'CertificadoNumeroSerie'  , $cfd['no_certificado']);
    $fecha          = $doc->createElementNS($ns, 'CertificadoFechaEmision' , $cfd['fecha']);
    //append created elements
    $folioC->appendChild($id);
    $folioC->appendChild($rfc);
    $folioC->appendChild($serie);
    $folioC->appendChild($folio);
    $folioC->appendChild($no_aprobacion);
    $folioC->appendChild($ano_aprobacion);
    $folioC->appendChild($no_certificado);
    $folioC->appendChild($fecha);
    //add folioC (folio container) to root
    $root->appendChild($folioC);
  }
  //append root to the document
  $doc->appendChild($root);

  // $schemaFileName = drupal_get_path('module', 'cfd') . '/resources/sat/SOAPrequest.xsd';
  // echo $doc->schemaValidate($schemaFileName) ? 'valido' : 'no valido';

  return $doc->saveXML();
}

/**
 * Envia una peticion SOAP al servidor SICOFI del SAT
 * @param string $xml el XML a enviar (sin validar)
 *  se espera que sea genrado con _cfd_generate_multi_request_xml(...)
 * @return stirng $xml
 */
function _cfd_sat_soap_request($xml) {
  $wsdl = 'https://tramitesdigitales.sat.gob.mx/Sicofi.wsExtValidacionCFD/WsValidacionCFDsExt.asmx?WSDL';
  $sat_soap = new SoapClient($wsdl);
  $response = $sat_soap->ValidarXmlCFD(array('xml' => $validationXML));
  return $response->ValidarXmlCFDResult;
}

/**
 * Interpreta la respuesta del sat
 * @param string $xml valor devuelto por _cfd_sat_soap_request(...)
 * @return array con Id como key y codigo de validacion del SAT como valor
 *  array('1' => 'VV', '2' => 'IV', ...)
 */
function _cfd_parse_sat_soap_response($xml) {
  $doc = new DOMDocument();
  $doc->preserveWhiteSpace = FALSE;
  $doc->loadXML($xml);
  $xpath = new DOMXPath($doc);
  $r_ids = $xpath->query('/cfd:RespuestaFoliosCfd/cfd:ResultadoValidacion/cfd:Id');
  foreach ($r_ids as $id_node) {
    // echo "|- $id_node->tagName -> $id_node->nodeValue\n";
    // print_r($id_node->nextSibling->nodeValue);
    $data[$id_node->nodeValue] = $id_node->nextSibling->nodeValue;
  }
  return $data;
}
