<?php
/**
 * @file Contains PDF creation functions based on TCPDF.
 * Also contatins Schema validation funcitons
 */

/**
 * Makes a PDF based on 2 XSL Template files (located in resources/cfd_*.xsl)
 * one for header, one for content and also uses SAT provided file: cadenaoriginal_2_0.xslt
 * Uses FEpdf class to define the header and footer (located in reources/FEpdf.php)
 * Custom code to word-wrap the 'cadena original' using | instead of spaces.
 * @param mixed $xml The xml string or .xml file of the CFD to convert to PDF
 * @return a TCPDF object of the converted CFD
 **/
function cfd_make_pdf($xml) {
  require_once libraries_get_path('tcpdf') . '/tcpdf.php';
  require_once drupal_get_path('module', 'cfd') . '/resources/FEpdf.php';
  //Apply XSLT
  $doc = new DOMDocument();
  //load xml data string or filename
  if (is_file($xml))
    $doc->load($xml, LIBXML_NOWARNING);
  else
    $doc->loadXML($xml);

  //Content
  $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/cfd_content.xsl';
  $xsl_content = new DOMDocument(); $xsl_content->load($xsl_content_file);
  $xsl = new XSLTProcessor(); $xsl->importStylesheet($xsl_content);
  $xsl->registerPHPFunctions('number_format');
  $html_content = $xsl->transformToXml($doc);
  //"cadena original" or cado
  $xsl_cado_file = drupal_get_path('module', 'cfd') . '/resources/sat/cadenaoriginal_2_0.xslt';
  $xsl_cado = new DOMDocument(); $xsl_cado->load($xsl_cado_file);
  // hide warnings in @...importStylesheet because it complains about xslt version 2.0
  $xsl = new XSLTProcessor(); @$xsl->importStylesheet($xsl_cado);
  $cadena_original = $xsl->transformToXml($doc);

  //generate PDF
  $pdf = new FEpdf();
  $pdf->SetMargins(10, 10, 10, TRUE);
  //Header (in FEpdf.php)
  $pdf->registerHeader($doc);
  $pdf->AddPage();

  $pdf->writeHTML($html_content.'<br />');

  //Cadena Original with word wrapping in |
  $pdf->SetY($pdf->getY() - 7);
  $pdf->SetFontSize(10);
  $pdf->writeHTML('<strong>Cadena Original</strong>');
  $pdf->SetFontSize(8);
  //word wrapping
  $cado = explode('|', substr($cadena_original, 2, -2));
  $pdf->SetCellPadding(0);
  $pdf->Write(0, '||');
  $margins = $pdf->getMargins();
  $line_width = $pdf->getPageWidth() - $margins['left'] - $margins['right'];
  $space_left = $line_width -  $pdf->GetStringWidth('||');
  $totalwords = count($cado);
  $i = 0;
  foreach ($cado as $word) {
    //if we are on the last word
    if ($i < $totalwords - 1) {
      $word_width = $pdf->GetStringWidth($word . '|');
    }
    else {
      $word_width = $pdf->GetStringWidth($word . '||');
    }

    if ($word_width > $space_left) {
      $space_left = $line_width - $word_width;
      $pdf->Ln();
    }
    else {
      $space_left -= $word_width;
    }
    $pdf->Write(0, $word . '|');
    $i++;
  }
  $pdf->Write(0, '|');
  //serve file
  $pdf->SetCreator("Drupal-CFD module with " . PDF_CREATOR);
  $pdf->SetAuthor(variable_get('site_name', 'the website'));
  return $pdf;
}

/**
 * Validates a CFD against cfdv2.xsd (XML Schema provided by SAT)
 * removes Addenda and Complemento nodes to avoid issues
 * @param mixed $xml filename or xml data to validate
 * @return bool true if it is a valid xml
 */
function cfd_validate_schema($xml) {
  $doc = new DOMDocument();
  //load xml data string or filename
  if (is_file($xml))
    $doc->load($xml, LIBXML_NOWARNING);
  else
    $doc->loadXML($xml);

  // gather problem nodes: Addenda, Complemento
  $doc_el = $doc->documentElement;
  $addenda_list     = $doc_el->getElementsByTagName('Addenda');
  $complemento_list = $doc_el->getElementsByTagName('Complemento');
  //remove these gathered nodes
  foreach($addenda_list as $addenda) {
    $doc_el->removeChild($addenda);
  }
  foreach($complemento_list as $complemento) {
    $doc_el->removeChild($complemento);
  }

  if ($doc->isDefaultNamespace('http://www.sat.gob.mx/cfd/2'))
    $schemaFileName = drupal_get_path('module', 'cfd') . '/resources/sat/cfdv2.xsd';
  else if ($doc->lookupPrefix('http://www.sat.gob.mx/cfd/3') == 'cfdi')
    $schemaFileName = drupal_get_path('module', 'cfd') . '/resources/sat/cfdv3.xsd';

  $validcfd = @$doc->schemaValidate($schemaFileName);
  return $validcfd;
}

/**
 * Validates the CFD's 'sello'
 * @param mixed $xml The xml string or .xml file of the CFD to convert to PDF
 * @return string valido, invalido or intdeterminado
 **/
function cfd_validate_sello($xml) {
  // get cadena original using SAT provided XSLT file.
  $doc = new DOMDocument();
  if (is_file($xml))
    $doc->load($xml, LIBXML_NOWARNING);
  else
    $doc->loadXML($xml);

  $xsl_content = new DOMDocument();
  $xpath = new DOMXPath($doc);
  if ($doc->isDefaultNamespace('http://www.sat.gob.mx/cfd/2')) {
    // for CFD
    $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/sat/cadenaoriginal_2_0.xslt';
    $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/2');
  }
  else if ($doc->lookupPrefix('http://www.sat.gob.mx/cfd/3') == 'cfdi') {
    // for CFDI
    $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/sat/cadenaoriginal_3_0.xslt';
    $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/3');
  }

  $year = substr($xpath->query('/cfd:Comprobante/@fecha')->item(0)->value, 0, 4);
  $certificado = $xpath->query('/cfd:Comprobante/@certificado');
  $sello = $xpath->query('/cfd:Comprobante/@sello')->item(0)->value;
  $xsl_content->load($xsl_content_file, LIBXML_NOWARNING);
  $xsl = new XSLTProcessor(); @$xsl->importStylesheet($xsl_content);
  $cadena_original = $xsl->transformToXml($doc);


  // Since @certificado is optional in a CFD
  if($certificado->length) {
    // convert $certificado into something openssl can parse
    // but first decode entities and remove whitespaces (and newlines, etc...)
    $cert = preg_replace('/\s+/', '', html_entity_decode($certificado->item(0)->value, ENT_QUOTES, 'UTF-8'));
    $pub_cer = "-----BEGIN CERTIFICATE-----\r\n";
    $pub_cer .= wordwrap($cert, 64, "\r\n", true);
    $pub_cer .= "\r\n-----END CERTIFICATE-----";
    $pub_key = openssl_pkey_get_public($pub_cer);

    if ($year <= 2010)
      $v = openssl_verify($cadena_original, base64_decode($sello), $pub_key, OPENSSL_ALGO_MD5);
    else
      $v = openssl_verify($cadena_original, base64_decode($sello), $pub_key, OPENSSL_ALGO_SHA1);

    if ($v == 1) {
      return 'valido';
    }
    else if ($v == 0) {
      return 'invalido';
    }
  } else
    return 'indeterminado';
}

function cfd_validate_folio($serie, $folio, $noAprobacion, $anoAprobacion, $emisor_rfc) {
}
