<?php
/**
 * @file Main module file
 */

define('TYPE_CFD' , 0);
define('TYPE_CFDI', 1);
define('CFD_INGRESO' , 0);
define('CFD_EGRESO'  , 1);
define('CFD_TRASLADO', 2);

/**
 * Implementation of hook_menu().
 */
function cfdr_menu() {
  $menu = array();
  $menu['cfdr'] = array(
    'title' => 'View CFDs',
    'description' => 'View all CFDs',
    'access callback' => 'user_access',
    'access arguments' => array('view any CFD'),
    'page callback' => 'cfdr_view_cfds',
    // 'page arguments' => array('cfdr_view_cfds'),
  );
  $menu['cfdr/%/xml'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'Download',
    'access callback' => 'user_access',
    'access arguments' => array('view any CFD'),
    'page callback' => 'cfdr_download_xml',
    'page arguments' => array(1),
  );
  // HTML view
  $menu['cfdr/%cfdr'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'View CFD',
    'access callback' => 'user_access',
    'access arguments' => array('view any CFD'),
    'page callback' => 'cfdr_view_single',
    'page arguments' => array(1),
  );
  $menu['cfdr/%/pdf'] = array(
    'type' => MENU_CALLBACK,
    'title' => 'View CFD',
    'access callback' => 'user_access',
    'access arguments' => array('view any CFD'),
    'page callback' => 'cfdr_download_pdf',
    'page arguments' => array(1),
  );
  //Admin menu
  $menu['admin/config/content/cfdr'] = array(
    'title' => 'CFD - Received Settings',
    'description' => 'Configure CFD - Received options',
    'access callback' => 'user_access',
    'access arguments' => array('administer cfdr'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cfdr_admin_form'),
    'file'=>'cfdr.admin.inc',
  );
  return $menu;
}

/**
 * Implementation of hook_theme()
 **/
function cfdr_theme() {
  return array(
    'cfdr_filters_fieldset' => array(
      'render element' => 'form'
    ),
    'cfdr_view_single_fieldset_form' => array(
      'render element' => 'form'
    ),
  );
}

/**
 * Implementation of hook_perm().
 */
function cfdr_permission() {
  return array(
    'administer cfdr' => array(
      'title' => t('Administer CFDr module'),
      'description' => t('Select directories to scan'),
    ),
    'view any CFD' => array(
      'title' => t('View CFDs'),
      'description' => t('Allows role to view any and all CFDs'),
    ),
  );
}

/**
 * Saves a fully loaded cfdr object to {cfdr}
 * @return If the record insert or update failed, returns FALSE.
 *  If it succeeded, returns SAVED_NEW or SAVED_UPDATED, depending on the operation performed.
 **/
function cfdr_save(&$cfdr) {
  return drupal_write_record('cfdr', $cfdr);
}

/**
 * Loads then reads, then inserts a CFD into de database.
 * @param string $cfdr_filename the full path and name of the CFD's .xml file
 **/
function cfdr_insert($filename) {
  //parse XML file read (with DOM XML(simpleXML sucks at namespaces))
  $doc = new DOMDocument();
  @$doc->load($filename, LIBXML_NOWARNING);
  $xpath = new DOMXPath($doc);
  $cfdr = new stdClass();
  // if we're dealing with CFD (and not CFDi)
  if ($doc->isDefaultNamespace('http://www.sat.gob.mx/cfd/2')) {
    $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/2');
    $cfdr->xml_type = TYPE_CFD;
  }
  else if ($doc->lookupPrefix('http://www.sat.gob.mx/cfd/3') == 'cfdi') {
    $xpath->registerNamespace('cfd', 'http://www.sat.gob.mx/cfd/3');
    $cfdr->xml_type = TYPE_CFDI;
  }
  $fecha_cfd = $xpath->query('/cfd:Comprobante/@fecha');
  // abort if not on a CFD or CFDI
  if (!$fecha_cfd->length) return FALSE;
  $cfdr->fecha_cfd       = $fecha_cfd->item(0)->value;
  $cfdr->serie           = $xpath->query('/cfd:Comprobante/@serie')->item(0)->value;
  $cfdr->folio           = $xpath->query('/cfd:Comprobante/@folio')->item(0)->value;
  $cfdr->no_aprobacion   = $xpath->query('/cfd:Comprobante/@noAprobacion')->item(0)->value;
  $cfdr->ano_aprobacion  = $xpath->query('/cfd:Comprobante/@anoAprobacion')->item(0)->value;
  $cfdr->emisor_rfc      = $xpath->query('/cfd:Comprobante/cfd:Emisor/@rfc')->item(0)->value;
  $cfdr->emisor_nombre   = $xpath->query('/cfd:Comprobante/cfd:Emisor/@nombre')->item(0)->value;
  $cfdr->receptor_rfc    = $xpath->query('/cfd:Comprobante/cfd:Receptor/@rfc')->item(0)->value;
  $cfdr->importe         = $xpath->query('/cfd:Comprobante/@total')->item(0)->value;
  $cfdr->no_certificado  = $xpath->query('/cfd:Comprobante/@noCertificado')->item(0)->value;
  $cfdr_type             = $xpath->query('/cfd:Comprobante/@tipoDeComprobante')->item(0)->value;
  $cfdr->xml_filename    = $filename;

  switch ($cfdr_type) {
    case 'ingreso':
      $cfdr->cfd_type = CFD_INGRESO;
    break;
    case 'egreso':
      $cfdr->cfd_type = CFD_EGRESO;
    break;
    case 'traslado':
      $cfdr->cfd_type = CFD_TRASLADO;
    break;
  }

  return cfdr_save($cfdr);
}

/**
 * Loads a cfdr object and returns it
 * @param int $cfdr_id Id of the CFD to retreive
 * @return stdObject a loaded node-like object.
 */
function cfdr_load($cfdr_id) {
  return db_query('SELECT * FROM {cfdr} WHERE cfdr_id=?', array($cfdr_id))->fetchObject();
}

/**
 * Returns the filename of a CFD
 * @param int $cfdr_id Id of the CFD to retreive
 */
function cfdr_load_filename($cfdr_id) {
  return db_query('SELECT xml_filename FROM {cfdr} WHERE cfdr_id=?', array($cfdr_id))->fetchField();
}

/**
 * 'cfdr' menu entry callback
 **/
function cfdr_view_cfds() {
  $query = db_select('cfdr', 'c')->fields('c');
  $filters = isset($_SESSION['cfdr_filters']) ? $_SESSION['cfdr_filters'] : NULL;
  if (isset($filters)) {
    foreach ($filters as $filter => $value) {
      switch ($filter) {
        // default:
        case 'receptor_rfc':
        case 'serie':
          $or = db_or();
          foreach ($value as $v) {
            if ($v == NULL)
              $or->isNull($filter);
            else
              $or->condition($filter, $v);
          }
          $query->condition($or);
        break;
        case 'fecha_cfd':
          if (isset($value['start']) && isset($value['end']))
            $query->condition(db_and()->condition('fecha_cfd', $value['start'], '>=')->condition('fecha_cfd', $value['end'], '<='));
          else if (!isset($value['start']) && isset($value['end']))
            $query->condition('fecha_cfd', $value['end'], '<=');
          else if (isset($value['start']) && !isset($value['end']))
            $query->condition('fecha_cfd', $value['start'], '>=');
        break;
        case 'emisor_nombre':
          $query->condition('emisor_nombre', '%%'.$value.'%%', 'LIKE');
        break;
        case 'valid':
          switch ($value) {
            case 1:
              $query->condition('valid', TRUE);
            break;
            case 2:
              $query->isNull('valid');
            break;
            case 3:
              $query->condition('valid', FALSE);
            break;
          }
        break;
        case 'navfc':
          if (trim($value) == 'NULL')
            $query->isNull('nav_number');
          else if (trim($value) == '*')
            $query->isNotNull('nav_number');
          else
            $query->condition('nav_number', $value);
        break;
      }
    }
  }

  $header = array(
    t('Status'),
    array('data' => 'Serie', 'field' => 'serie'),
    array('data' => 'Folio', 'field' => 'folio'),
    array('data' => t('Emisor'), 'field' => 'emisor_rfc'),
    array('data' => t('Date'), 'field' => 'fecha_cfd', 'sort' => 'desc'),
    array('data' => t('Receptor'), 'field' => 'receptor_rfc'),
    array('data' => '$', 'field' => 'importe'),
    array('data' => 'NAV FC', 'field' => 'nav_number'),
    // 'Archivo',
    // array('data' => 'archivo', 'field' => 'xml_filename'),
    // t('Download'),
  );
  // drupal_set_message((string) $query);
  $query = $query->extend('PagerDefault')->limit(30)->extend('TableSort')->orderByHeader($header);
  $results = $query->execute();

  $r = 0; // row number iterator
  $i = 1; // even-odd iterator
  foreach ($results as $cfd) {
    $basename = basename($cfd->xml_filename);
    $name = substr($basename, 0, strrpos($basename, '.'));
    $fecha = new DateObject($cfd->fecha_cfd, date_default_timezone(), DATE_FORMAT_DATETIME);
    $rows[$r++] = array(
      'data' => array(
        array('data' => cfdr_validity_image($cfd->valid, $cfd->cfdr_id), 'style' => 'text-align:center;'),
        $cfd->serie,
        $cfd->folio,
        (strlen($cfd->emisor_nombre) >=50)
          ? array('data' => substr($cfd->emisor_nombre, 0, 47) . '...', 'title'=>$cfd->emisor_nombre)
          : $cfd->emisor_nombre,
        format_date($fecha->format(DATE_FORMAT_UNIX), 'custom', 'j M Y'),
        $cfd->receptor_rfc,
        array('data' => '$' . number_format($cfd->importe, 2), 'style' => 'text-align:right;'),
        $cfd->nav_number,
      ),
      'no_striping' => TRUE,
      'class' => ($i % 2 == 0) ? 'even' : 'odd',
    );
    $rows[$r++] = array(
      'data' => array(
        // array('data' => 'Archivo', 'header' => TRUE),
        array('data' => 'Archivo -&gt;', 'style' =>'font-style:italic; font-weight: bolder;'),
        array('data' => l($basename, "cfdr/{$cfd->cfdr_id}/xml", array('attributes'=>array('title'=>$cfd->xml_filename))), 'colspan' => 6 ),
        array('data' => l(t('View'), "cfdr/{$cfd->cfdr_id}")),
      ),
      'no_striping' => TRUE,
      'class' => ($i++ % 2 == 0) ? 'even' : 'odd',
    );
  }

  return drupal_render(drupal_get_form('cfdr_filters_form')) .
    theme('table', array('header' => $header, 'rows' => $rows, 'empty' => t('No CFDs available.'))) .
    theme('pager', array('tags' => array()));
}

/**
 * filter form for 'cfdr' menu entry callback
 **/
function cfdr_filters_form() {
  // cfd_include_datepick();
  $form['filters'] = array(
    '#type' => 'fieldset',
    '#title' => t('Filter'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['filters']['serie'] = array(
    '#type' => 'select',
    '#title' => 'Serie',
    '#default_value' => @array_keys($_SESSION['cfdr_filters']['serie']),
    '#options' => _cfdr_get_select('serie'),
    '#multiple' => TRUE,
    '#size' => 10,
  );
  $form['filters']['emisor_nombre'] = array(
    '#type' => 'textfield',
    '#title' => 'Nombre emisor',
    '#size' => 50,
    '#maxlength' => 255,
    '#default_value' => $_SESSION['cfdr_filters']['emisor_nombre'],
    '#description' => 'Nombre o parte del nombre<br/>&nbsp;'
  );
  // RFCs
  // $form['filters']['emisor_rfc'] = array(
  //   '#type' => 'select',
  //   '#title' => 'RFC Emisor',
  //   '#default_value' =>  @array_keys($_SESSION['cfdr_filters']['emisor_rfc']),
  //   '#options' => _cfdr_get_select('emisor_rfc'),
  //   '#multiple' => TRUE,
  // );
  $form['filters']['receptor_rfc'] = array(
    '#type' => 'select',
    '#title' => 'RFC Receptor',
    '#default_value' =>  @array_keys($_SESSION['cfdr_filters']['receptor_rfc']),
    '#options' => _cfdr_get_select('receptor_rfc'),
    '#multiple' => TRUE,
  );
  // Date filter
  $form['filters']['fecha_cfd']['start'] = array(
    '#type' => 'textfield',
    '#title' => t('Start date'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Format: yyyy-mm-dd'),
    '#default_value' => substr($_SESSION['cfdr_filters']['fecha_cfd']['start'], 0, 10),
  );
  $form['filters']['fecha_cfd']['end'] = array(
    '#type' => 'textfield',
    '#title' => t('End date'),
    '#size' => 10,
    '#maxlength' => 10,
    '#description' => t('Format: yyyy-mm-dd'),
    '#default_value' => substr($_SESSION['cfdr_filters']['fecha_cfd']['end'], 0, 10),
  );
  $form['filters']['valid'] = array(
    '#type' => 'radios',
    '#title' => t('Status'),
    '#default_value' => $_SESSION['cfdr_filters']['valid'],
    '#options' => array(
      t('All'),
      theme('image', array('path'=>'misc/watchdog-ok.png')),
      theme('image', array('path'=>'misc/watchdog-warning.png')),
      theme('image', array('path'=>'misc/watchdog-error.png')),
    ),
  );
  $form['filters']['navfc'] = array(
    '#type' => 'textfield',
    '#title' => 'NAV FC',
    '#size' => 15,
    '#maxlength' => 11,
    '#default_value' => $_SESSION['cfdr_filters']['navfc'],
    '#description' => 'Número completo. <em>*</em> busca cualquier número<br/><em>NULL</em> busca los que no tienen número.'
  );

  // Buttons
  $form['filters']['filter'] = array(
    '#type' => 'submit',
    '#value' => t('Filter'),
  );
  $form['filters']['reset'] = array(
    '#type' => 'submit',
    '#value' => t('Reset'),
  );
  $form['filters']['#theme'] = 'cfdr_filters_fieldset';
  $form['#submit'][] = 'cfdr_filters_form_submit';
  return $form;
}

/**
 *
 **/
function cfdr_filters_form_submit($form, &$form_state) {
  unset($_SESSION['cfdr_filters']);
  if ($form_state['values']['op'] == t('Reset')) {
    return;
  }
  $filters = &$_SESSION['cfdr_filters'];
  $values = $form_state['values'];
  // dpm($form);

  // foreach ($values['emisor_rfc'] as $key)
  //   $filters['emisor_rfc'][$key] = $form['filters']['emisor_rfc']['#options'][$key];

  foreach ($values['serie'] as $key)
    $filters['serie'][$key] = $form['filters']['serie']['#options'][$key];

  foreach ($values['receptor_rfc'] as $key)
    $filters['receptor_rfc'][$key] = $form['filters']['receptor_rfc']['#options'][$key];

  if ($values['start']) {
    $start = date_create($values['start']);
    $filters['fecha_cfd']['start'] = date_format($start, DATE_FORMAT_ISO);
  }
  if ($values['end']) {
    $end = date_create($values['end']);
    $end->modify('+23 hours 59 minutes 59 seconds');
    $filters['fecha_cfd']['end'] = date_format($end, DATE_FORMAT_ISO);
  }
  if ($values['emisor_nombre']) {
    $filters['emisor_nombre'] = $values['emisor_nombre'];
  }
  if ($values['valid']) {
    $filters['valid'] = $values['valid'];
  }
  if ($values['navfc']) {
    $filters['navfc'] = $values['navfc'];
  }
}

/**
 * used to populate fields in cfdr_filter_form()
 *
 **/
function _cfdr_get_select($field) {
  $query = db_select('cfdr', 'c')->groupBy('c.'.$field)->orderBy('c.'.$field);
  $query->addField('c', $field);
  $results = $query->execute()->fetchAll();
  $options = array();
  foreach ($results as $r)
    $options[] = $r->$field;
  return $options;
}

/**
 * Theme for for cfdr_filter_form()
 **/
function theme_cfdr_filters_fieldset($variables) {
  $form = $variables['form'];
  $output = '';
  $output .= '<div style="display: inline-block;">';
    $output .= '<div style="display: inline-block; padding-right: 15px">' . drupal_render($form['emisor_nombre']) . '</div>';
    $output .= '<div style="display: inline-block;">' . drupal_render($form['navfc']) . '</div>';
  $output .= '</div><div style="display: table-row;">';
    $output .= '<div style="display: table-cell;">' . drupal_render($form['serie']) . '</div>';
    $output .= '<div style="display: table-cell; padding-right: 30px">' . drupal_render($form['receptor_rfc']) . '</div>';
    $output .= '<div style="display: table-cell;">' . drupal_render($form['valid']) . '</div>';
  $output .= '</div><div style="display: table-row;">';
    $output .= '<div style="display: table-cell; padding-right: 15px">' . drupal_render($form['fecha_cfd']['start']) . '</div>';
    $output .= '<div style="display: table-cell;">' . drupal_render($form['fecha_cfd']['end']) . '</div>';
  $output .= '</div>';
  $output .= drupal_render($form['valid']);
  $output .= drupal_render($form['filter']) . drupal_render($form['reset']);
  return $output;
}

/*
 * Visualize a single CFD in a HTML page
 */
function cfdr_view_single($cfd) {
  drupal_set_breadcrumb(array(l(t('Home'), ''), l('Ver CFDs', 'cfdr')));
  drupal_set_title("$cfd->serie $cfd->folio" . ' - ' . /*l('PDF', "cfdr/$cfd->cfdr_id/pdf") . ' - ' . */l('xml', "cfdr/$cfd->cfdr_id/xml"), PASS_THROUGH);
  drupal_add_css(
    '.validstatusR {color:white; font-weight:bold; text-align:center; background-color: red;}
    .validstatusY {color:grey; font-weight:bold; text-align:center; background-color: yellow;}
    .validstatusG {color:white; font-weight:bold; text-align:center; background-color: green;}'
    , array('type' => 'inline'));

  $doc = new DOMDocument();
  $doc->load($cfd->xml_filename, LIBXML_NOWARNING);
  //chosse XSL file for CFD or CFDI
  if ($cfd->xml_type == TYPE_CFD)
    $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/cfd_html.xsl';

  elseif ($cfd->xml_type == TYPE_CFDI)
    $xsl_content_file = drupal_get_path('module', 'cfd') . '/resources/cfdi_html.xsl';

  $xsl_content = new DOMDocument(); $xsl_content->load($xsl_content_file);
  $xsl = new XSLTProcessor(); $xsl->importStylesheet($xsl_content);
  $xsl->registerPHPFunctions('number_format');
  $html_content = $xsl->transformToXml($doc);

  $struct_valid = cfd_validate_schema($cfd->xml_filename);
  $sello_valid = cfd_validate_sello($cfd->xml_filename);
  $cert_valid = cfd_validate_cert($cfd->no_certificado, $cfd->emisor_rfc, $cfd->fecha_cfd);
  $folio_valid = cfd_validate_folio($cfd->serie, $cfd->folio, $cfd->no_aprobacion, $cfd->ano_aprobacion, $cfd->emisor_rfc);
  drupal_set_message("$cfd->serie, $cfd->folio, $cfd->no_aprobacion, $cfd->ano_aprobacion, $cfd->emisor_rfc");
  $header = array(
    array('data' => 'Estructura XML (parcial)'),
    array('data' => 'Sello'),
    array('data' => 'Certificado'),
    array('data' => 'Folio'),
  );
  $rows = array(
    array(
      'no_striping' => TRUE,
      'data' => array(
        array(
          'data' => $struct_valid ? 'Valido' : 'Invalido',
          'class' => $struct_valid ? 'validstatusG' : 'validstatusR',
          'style' => 'width: 25%;',
        ),
        array(
          'data' => $sello_valid,
          'class' => ($sello_valid == 'indeterminado' ? 'validstatusY' : ($sello_valid == 'valido' ? 'validstatusG' : 'validstatusR')),
          'style' => 'width: 25%;',
        ),
        array(
          'data' => 'Validez Cert',
          'class' => $cert_valid ? 'validstatusG' : 'validstatusR',
          'style' => 'width: 25%;',
        ),
        array(
          'data' => 'Validez Folio',
          'class' => $folio_valid ? 'validstatusG' : 'validstatusR',
          'style' => 'width: 25%;',
        ),
      ),
    ),
    array('no_stripping' => TRUE, 'data' => array(array('data' => '&nbsp;', 'style' => 'background-color: white;', 'colspan' => 4))),
    array(
      'no_striping' => TRUE,
      'data' => array(  
        array(
          'data' => 'Status',
          'header' => TRUE,
          'style' => 'width: 25%;',
        ),
        array(
          'data' => cfdr_validity_image($cfd->valid, $cfd->cfdr_id),
          'style' => 'width: 25%;',
        ),
        array(
          'data' => 'NAV FC-',
          'header' => TRUE,
          'style' => 'width: 25%;',
        ),
        array(
          'data' => $cfd->nav_number,
          'style' => 'width: 25%;',
        ),
      ),
    ),
  );
  $r_array = array(
    'content' => array(
      '#markup' => $html_content,
    ),
  );

  return theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => array('style' => 'width:100%;'))) .
    drupal_render(drupal_get_form('cfdr_view_single_form', &$cfd)) .
    drupal_render($r_array);
}

/**
 * CFD status (valid) and nav_number edit form
 */
function cfdr_view_single_form($form, &$form_state, $cfd) {
  $form['efield'] = array(
    '#type' => 'fieldset',
    '#title' => t('Edit'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );
  $form['efield']['cfd_id'] = array(
    '#type' => 'hidden',
    '#value' => $cfd->cfdr_id,
  );

  $form['efield']['valid'] = array(
    '#type' => 'radios',
    '#title' => t('Status'),
    '#default_value' => _cfdr_valid2option($cfd->valid),
    '#options' => array(
      theme('image', array('path'=>'misc/watchdog-ok.png')),
      theme('image', array('path'=>'misc/watchdog-warning.png')),
      theme('image', array('path'=>'misc/watchdog-error.png')),
    ),
  );
  $form['efield']['nav_number'] = array(
    '#type' => 'textfield',
    '#title' => 'NAV FC-',
    '#default_value' => $cfd->nav_number,
    '#description' => 'Número de documento de NAV<br/>User números negativos (-1) para cancelados',
  );
  // Buttons
  $form['efield']['update'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
  );
  $form['efield']['#theme'] = 'cfdr_view_single_fieldset_form';
  $form['#submit'][] = 'cfdr_view_single_form_submit';
  return $form;
}

function cfdr_view_single_form_submit($form, &$form_state) {
  // dpm($form, 'form');
  // dpm($form_state, 'state');
  $cfd_id = $form_state['values']['cfd_id'];
  $valid = $form_state['values']['valid'];
  $nav_number = $form_state['values']['nav_number'];

  if (strlen($nav_number) == 0) unset($nav_number);
  // turn valid from option value to DB value
  switch ($valid) {
    case 0:
      $valid = 1; //TRUE
    break;
    case 1:
      unset($valid); //NULL
    break;
    case 2:
      $valid = 0; //FALSE
    break;
  }
  $update = array(
    'cfdr_id' => $cfd_id,
    'valid' => $valid,
    'nav_number' => $nav_number,
  );
  // dpm($update, 'updt');
  drupal_write_record('cfdr', $update, 'cfdr_id');

}
/**
 * from DB value to option value
 * @return $valid as an option:
 *  0-FALSE into 2
 *  1-TRUE into 0
 *  NULL into 1
 */
function _cfdr_valid2option($valid) {
  if (isset($valid)) {
    switch ($valid) {
    case FALSE:
      $valid = 2; //TRUE
    break;
    case TRUE:
      $valid = 0; //FALSE
    break;
    }
  } else
    $valid = 1;

  return $valid;
}

/**
 * Theme for cfdr_view_single_form fieldset
 */
function theme_cfdr_view_single_fieldset_form($variables) {
  $form = $variables['form'];
  $output = '<table><tr style="background-color: white;">';
    $output .= '<td style="width: 50%;">' . drupal_render($form['valid']) . '</td>';
    $output .= '<td style="width: 50%;">' . drupal_render($form['nav_number']) . '</td>';
  $output .= '</tr></table>';
  $output .= drupal_render($form['update']);
  return $output;
}

/**
 * Returns the xml file of the cfd node for download.
 * @param StdObject $node
 */
function cfdr_download_xml($cfdr_id) {
  $filename = cfdr_load_filename($cfdr_id);
  $basename = basename($filename);

  // Code based on file_transfer() but modified to serve files outside the
  // drupal file system
  if (ob_get_level()) {
    ob_end_clean();
  }

  // Transfer file in 1024 byte chunks to save memory usage.
  if ($fd = fopen($filename, 'rb')) {
    drupal_add_http_header('Content-Description', 'File Transfer');
    drupal_add_http_header('Content-Disposition',  'attachment; filename='.$basename, TRUE);
    drupal_add_http_header('Content-type', 'text/xml', TRUE);
    while (!feof($fd)) {
      print fread($fd, 1024);
    }
    fclose($fd);
  }
  else {
    drupal_not_found();
  }
  exit();
}

/**
 * Gets the out of the node and gets the PDF from cfd_make_pdf() then
 * sends it to the browser.
 * @param StdObject $node
 */
function cfdr_download_pdf($cfdr_id) {
  //generate PDF
  $pdf = cfd_make_pdf(cfdr_load_filename($cfdr_id));
  //send generated file to browser
  // $pdf->SetTitle($node->title);
  // $pdf->SetDisplayMode('fullpage');
  // $pdf->Output("$node->title.pdf");
  $pdf->Output();
}

/**
 * Get the appropriate image for valid, invalid, and to be determined CFD validity
 *
 **/
function cfdr_validity_image($status, $cfd_id) {
  switch ($status) {
    case NULL:
      return theme('image', array('path'=>'misc/watchdog-warning.png'));
      // return l(theme('image', array('path'=>'misc/watchdog-warning.png', 'title'=>'Click para validar')), "cfdr/$cfd_id/validar", array('html' => TRUE));
      break;
    case TRUE:
      return theme('image', array('path'=>'misc/watchdog-ok.png'));
      break;
    case FALSE:
      return theme('image', array('path'=>'misc/watchdog-error.png'));
      break;
  }
}

/*
 * Implementation of hook_cron().
 */
function cfdr_cron() {
  cfdr_scan();
}

/**
 * Scans for .xml cfds in configured directory and moves XML CFDs into $to_dir
 * $to_dir is named MMYYYY so it groups CFDs
 **/
function cfdr_scan() {
  $scan_path = variable_get('cfdr_scan_path', 'sites/default/cfd/new'); // new XMLs directory
  $fail_path = variable_get('cfdr_fail_path', 'sites/default/cfd/fail'); // move failed (non-CFD) XMLs to this dir
  $move_to = variable_get('cfdr_move_path', 'sites/default/cfd'); //base directory
  $to_dir = date('mY'); //monthly directory
  $move_path = $move_to . '/' . $to_dir; //move CFDs into here

  if ($files = file_scan_directory($scan_path, '/.*\.(xml|XML)$/')) {
    $count = 0;
    if (!is_dir($move_path)) {
      if (file_prepare_directory($move_path, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS))
        file_create_htaccess($move_path);
    }
    foreach ($files as $file) {
      if ($count > 100) break;
      $new_filename = $move_path . '/' . $file->filename;
      if ($resulting_fileuri = file_unmanaged_move($file->uri, $new_filename)) {
        // add entry to {cfdr} from .xml file
        if (cfdr_insert($resulting_fileuri)) {
          $count++;
        }
        else {
          file_unmanaged_move($resulting_fileuri, $fail_path . '/' . basename($resulting_fileuri));
        }
      }
    }
  }
  if ($count > 0)
    watchdog('cfdr', '@count files imported succesfully', array('@count' => $count), WATCHDOG_NOTICE);
}
